### ISSUE TITLE
Something is missing in your 'README' file. 

### ISSUE THREAD

**Issue by Nadelessar** [YopSolo/UnityBoltPlatformer#5]
Hi YopSolo, I noticed your 'README' file was missing a line.
[README_Nadelessar.md](https://github.com/YopSolo/UnityBoltPlatformer/files/8398751/README_Nadelessar.md)
Here's a version with the missing line.  

Best regards, 
Nadir

**Comment by YopSolo** [comment]
malin, mais il faudra le faire dans les règles de l'art vendredi :)
